import type { Contact, ContactActivity } from '@/types';

// ============================================================================
// MOCK CONTACTS
// ============================================================================

export const mockContacts: Contact[] = [
  {
    id: 'contact-001',
    firstName: 'Roberto',
    lastName: 'Sánchez',
    email: 'roberto.sanchez@email.com',
    phone: '+52 55 1234 5678',
    type: ['comprador'],
    status: 'cliente',
    leadSource: 'web',
    leadScore: 'caliente',
    assignedTo: 'agent-1',
    tags: ['VIP', 'Polanco', 'Premium'],
    notes: 'Interesado en propiedades de lujo en Polanco. Presupuesto alto.',
    propertyInterests: ['prop-001', 'prop-002'],
    budget: 15000000,
    currency: 'MXN',
    preferredNeighborhoods: ['Polanco', 'Lomas'],
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-02-12T14:30:00Z',
    lastContactDate: '2024-02-12T14:30:00Z',
  },
  {
    id: 'contact-002',
    firstName: 'María',
    lastName: 'González',
    email: 'maria.gonzalez@email.com',
    phone: '+52 33 2345 6789',
    type: ['comprador', 'inversionista'],
    status: 'prospecto',
    leadSource: 'facebook',
    leadScore: 'caliente',
    assignedTo: 'agent-2',
    tags: ['Inversionista', 'Múltiples propiedades'],
    notes: 'Busca departamentos para rentar en Guadalajara. Portfolio de inversión.',
    propertyInterests: ['prop-009', 'prop-010'],
    budget: 5000000,
    currency: 'MXN',
    preferredNeighborhoods: ['Providencia', 'Chapalita'],
    createdAt: '2024-01-15T11:30:00Z',
    updatedAt: '2024-02-11T16:15:00Z',
    lastContactDate: '2024-02-10T10:00:00Z',
  },
  {
    id: 'contact-003',
    firstName: 'Carlos',
    lastName: 'Ramírez',
    email: 'carlos.ramirez@empresa.com',
    phone: '+52 81 3456 7890',
    type: ['comprador'],
    status: 'prospecto',
    leadSource: 'google',
    leadScore: 'tibio',
    assignedTo: 'agent-3',
    tags: ['Ejecutivo', 'Mudanza'],
    notes: 'Se muda a Monterrey por trabajo. Busca casa familiar.',
    propertyInterests: ['prop-011'],
    budget: 8000000,
    currency: 'MXN',
    preferredNeighborhoods: ['San Pedro', 'Valle Oriente'],
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2024-02-13T11:20:00Z',
    lastContactDate: '2024-02-08T15:00:00Z',
  },
  {
    id: 'contact-004',
    firstName: 'Ana',
    lastName: 'Martínez',
    email: 'ana.martinez@email.com',
    phone: '+52 55 4567 8901',
    type: ['arrendatario'],
    status: 'lead',
    leadSource: 'instagram',
    leadScore: 'tibio',
    assignedTo: 'agent-1',
    tags: ['Joven profesional', 'Pet friendly'],
    notes: 'Busca departamento amueblado en Roma Norte. Tiene mascota.',
    propertyInterests: ['prop-004'],
    budget: 35000,
    currency: 'MXN',
    preferredNeighborhoods: ['Roma', 'Condesa'],
    createdAt: '2024-02-08T14:00:00Z',
    updatedAt: '2024-02-12T09:30:00Z',
    lastContactDate: '2024-02-11T12:00:00Z',
  },
  {
    id: 'contact-005',
    firstName: 'Luis',
    lastName: 'Hernández',
    email: 'luis.hernandez@startup.io',
    phone: '+52 55 5678 9012',
    type: ['arrendatario'],
    status: 'prospecto',
    leadSource: 'referido',
    leadScore: 'caliente',
    assignedTo: 'agent-4',
    tags: ['Startup', 'Oficina'],
    notes: 'Busca oficina para startup en crecimiento. 20 personas.',
    propertyInterests: ['prop-008'],
    budget: 150000,
    currency: 'MXN',
    preferredNeighborhoods: ['Santa Fe', 'Insurgentes'],
    createdAt: '2024-01-28T10:00:00Z',
    updatedAt: '2024-02-13T10:15:00Z',
    lastContactDate: '2024-02-13T10:15:00Z',
  },
  {
    id: 'contact-006',
    firstName: 'Patricia',
    lastName: 'Torres',
    email: 'patricia.torres@email.com',
    phone: '+52 55 6789 0123',
    type: ['vendedor'],
    status: 'cliente',
    leadSource: 'web',
    leadScore: 'caliente',
    assignedTo: 'agent-1',
    tags: ['Vendedor', 'Herencia'],
    notes: 'Necesita vender casa heredada en Condesa. Urgente.',
    propertyInterests: [],
    createdAt: '2024-02-05T11:00:00Z',
    updatedAt: '2024-02-12T16:00:00Z',
    lastContactDate: '2024-02-12T16:00:00Z',
  },
  {
    id: 'contact-007',
    firstName: 'Jorge',
    lastName: 'Flores',
    email: 'jorge.flores@email.com',
    phone: '+52 33 7890 1234',
    type: ['comprador'],
    status: 'lead',
    leadSource: 'whatsapp',
    leadScore: 'frio',
    assignedTo: 'agent-2',
    tags: ['Primera vez'],
    notes: 'Primer compra. Necesita asesoría sobre crédito.',
    propertyInterests: [],
    budget: 3000000,
    currency: 'MXN',
    createdAt: '2024-02-12T08:30:00Z',
    updatedAt: '2024-02-12T08:30:00Z',
  },
  {
    id: 'contact-008',
    firstName: 'Sandra',
    lastName: 'Morales',
    email: 'sandra.morales@corp.com',
    phone: '+52 55 8901 2345',
    type: ['arrendatario'],
    status: 'prospecto',
    leadSource: 'email',
    leadScore: 'caliente',
    assignedTo: 'agent-4',
    tags: ['Corporativo', 'Ejecutivo'],
    notes: 'Empresa busca departamento amueblado para ejecutivo extranjero.',
    propertyInterests: ['prop-007'],
    budget: 50000,
    currency: 'MXN',
    preferredNeighborhoods: ['Santa Fe', 'Polanco'],
    createdAt: '2024-02-03T09:00:00Z',
    updatedAt: '2024-02-11T14:00:00Z',
    lastContactDate: '2024-02-11T14:00:00Z',
  },
  {
    id: 'contact-009',
    firstName: 'Miguel',
    lastName: 'Vargas',
    email: 'miguel.vargas@email.com',
    phone: '+52 81 9012 3456',
    type: ['inversionista'],
    status: 'cliente',
    leadSource: 'referido',
    leadScore: 'caliente',
    assignedTo: 'agent-3',
    tags: ['VIP', 'Inversionista', 'Alto patrimonio'],
    notes: 'Inversionista de alto patrimonio. Portfolio de 10+ propiedades.',
    propertyInterests: ['prop-011', 'prop-012'],
    budget: 50000000,
    currency: 'MXN',
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-02-13T15:30:00Z',
    lastContactDate: '2024-02-13T15:30:00Z',
  },
  {
    id: 'contact-010',
    firstName: 'Laura',
    lastName: 'Castillo',
    email: 'laura.castillo@email.com',
    phone: '+52 55 0123 4567',
    type: ['comprador'],
    status: 'inactivo',
    leadSource: 'walk-in',
    leadScore: 'frio',
    assignedTo: 'agent-1',
    tags: ['Inactivo'],
    notes: 'No respondió últimos 3 seguimientos.',
    propertyInterests: ['prop-005'],
    budget: 10000000,
    currency: 'MXN',
    createdAt: '2023-12-10T11:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
    lastContactDate: '2024-01-15T14:00:00Z',
  },
];

// ============================================================================
// MOCK CONTACT ACTIVITIES
// ============================================================================

export const mockContactActivities: ContactActivity[] = [
  {
    id: 'activity-001',
    contactId: 'contact-001',
    type: 'call',
    title: 'Llamada de seguimiento',
    description: 'Discutimos opciones en Polanco. Muy interesado en prop-001.',
    createdBy: 'agent-1',
    createdAt: '2024-02-12T14:30:00Z',
  },
  {
    id: 'activity-002',
    contactId: 'contact-001',
    type: 'property-view',
    title: 'Visita a propiedad',
    description: 'Visitó prop-001. Le encantó el jardín y la cocina.',
    createdBy: 'agent-1',
    createdAt: '2024-02-10T11:00:00Z',
  },
  {
    id: 'activity-003',
    contactId: 'contact-002',
    type: 'email',
    title: 'Envío de opciones',
    description: 'Envié 3 opciones de departamentos en Providencia.',
    createdBy: 'agent-2',
    createdAt: '2024-02-11T16:15:00Z',
  },
  {
    id: 'activity-004',
    contactId: 'contact-005',
    type: 'meeting',
    title: 'Reunión en oficina',
    description: 'Reunión para discutir necesidades de espacio y presupuesto.',
    createdBy: 'agent-4',
    createdAt: '2024-02-13T10:15:00Z',
  },
  {
    id: 'activity-005',
    contactId: 'contact-009',
    type: 'whatsapp',
    title: 'Mensaje de WhatsApp',
    description: 'Envió fotos de prop-011. Solicitó agendar visita.',
    createdBy: 'agent-3',
    createdAt: '2024-02-13T15:30:00Z',
  },
];

// ============================================================================
// CONTACT STATS
// ============================================================================

export function getContactStats() {
  const stats = {
    total: mockContacts.length,
    leads: 0,
    prospectos: 0,
    clientes: 0,
    inactivos: 0,
    conversionRate: 0,
    averageLeadScore: 0,
  };

  let leadScoreSum = 0;
  const leadScoreValues = { frio: 1, tibio: 2, caliente: 3 };

  mockContacts.forEach((contact) => {
    // Map singular status to plural stats keys
    if (contact.status === 'lead') stats.leads++;
    else if (contact.status === 'prospecto') stats.prospectos++;
    else if (contact.status === 'cliente') stats.clientes++;
    else if (contact.status === 'inactivo') stats.inactivos++;

    leadScoreSum += leadScoreValues[contact.leadScore];
  });

  stats.conversionRate = (stats.clientes / stats.total) * 100;
  stats.averageLeadScore = leadScoreSum / stats.total;

  return stats;
}
